[workspace]
resolver = "2"
members = [
    "demo",
    "kernel",
]

[profile.dev]
panic = "abort"
lto = true # true
opt-level = 0 # "z"
debug = true

[profile.release]
panic = "abort"
lto = true
opt-level = 0 # "z"
debug = true
codegen-units = 1
