[target.thumbv7em-none-eabihf]
rustflags = [
    # order of linker arguments is important
    "-C", "link-arg=-Tdemo/mps2_an385.x", 
    "-C", "link-arg=-Tdemo/common.x", 
    "-C", "link-args=-Map=./target/demo.map"
]

runner = "./scripts/qemu-runner.sh"

[build]
target = "thumbv7em-none-eabihf"
