[target.thumbv7em-none-eabihf]
rustflags = ["-C", "link-arg=-Tdemo/mps2_an385.x", "-C", "link-args=-Map=./target/demo.map"]

runner = "./scripts/qemu-runner.sh"

[build]
target = "thumbv7em-none-eabihf"
